using Content.Server._NF.Shipyard.Systems;
using Content.Shared._AS.Shuttles.Deeds;
using Content.Shared._NF.Shipyard.Components;
using Content.Shared.Access.Components;
using Content.Shared.Station.Components;

namespace Content.Server._AS.Shuttles.Deeds;

public sealed class AutoGenerateDeedSystem : SharedAutoGenerateDeedSystem
{
    [Dependency] private readonly EntityManager _entMan = default!; // Aurora's Song - Use entity manager

    public override void Initialize()
    {
        base.Initialize();

        SubscribeLocalEvent<AutoGenerateDeedComponent, MapInitEvent>(OnMapInit);
    }

    private void OnMapInit(EntityUid uid, AutoGenerateDeedComponent component, MapInitEvent args)
    {
        // Eagerly try to assume grid deed
        var grid = TryAssignGridDeed(uid, component);

        // If deed cannot be found from local grid, try searching outside grids
        if (grid == null && component.StationName != null)
        {
            var query = EntityQueryEnumerator<StationMemberComponent, MetaDataComponent>();
            while (query.MoveNext(out var stationUid, out _, out var metaData)) // Find the station that matches what we are given
            {
                if (component.StationName != metaData.EntityName) // This works under the assumption that majour stations can't be renamed.
                    continue;

                Log.Debug($"AssignDeeds called with iduid={uid}, shuttleuid={stationUid}, name={metaData.EntityName}");
                AssignDeeds(uid, stationUid, metaData, false, false);
                grid = stationUid;
                break; // If there's somehow two POI's with the same name, cry a little
            }
        }

        if (grid == null)
        {
            Log.Warning($"Deed autogeneration failed for entity {uid}, parameters: {component.StationName}");
            return;
        }

        if (!component.Unique)
            return;

        var idQuery = EntityQueryEnumerator<ShuttleDeedComponent, IdCardComponent>();
        while (idQuery.MoveNext(out var otherId, out var deed, out _)) // If this is a unique shuttle deed, we want to remove the deed from any other ID's that link to our grid
        {
            if (uid == otherId) // Don't want to wipe our ID
                continue;

            if (deed.ShuttleUid == grid)
                RemComp<ShuttleDeedComponent>(otherId);
        }
    }

    private void AssignDeeds(EntityUid idUid, EntityUid shuttleUid, MetaDataComponent shuttleMeta, bool sellable, bool shuttle)
    {
        var deedId = EnsureComp<ShuttleDeedComponent>(idUid);
        if (shuttle) // Shuttles have fancier names
        {
            ShipyardSystem.TryParseShuttleName(deedId, shuttleMeta.EntityName);
        }
        else
        {
            deedId.ShuttleName = shuttleMeta.EntityName;
        }
        deedId.ShuttleUid = shuttleUid;
        deedId.Sellable = sellable;

        Entity<ShuttleDeedComponent> ent = (idUid, deedId);
        Dirty(ent);

        var deedStation = EnsureComp<ShuttleDeedComponent>(shuttleUid);
        if (shuttle) // Shuttles have fancier names
        {
            ShipyardSystem.TryParseShuttleName(deedStation, shuttleMeta.EntityName);
        }
        else
        {
            deedId.ShuttleName = shuttleMeta.EntityName;
        }
        deedStation.ShuttleUid = shuttleUid;
        deedStation.Sellable = sellable;
    }

    /// <summary>
    ///     Logic for auto generating deeds that can be spawned on any viable grid to generate it a Deed
    /// </summary>
    private EntityUid? TryAssignGridDeed(EntityUid uid, AutoGenerateDeedComponent component)
    {
        if (!_entMan.TryGetComponent<TransformComponent>(uid, out var transform) || transform.GridUid is not { } gridUid || // Aurora's Song - Use entity manager
            !_entMan.TryGetComponent<MetaDataComponent>(gridUid, out var shuttleMeta)) // Aurora's Song - Use entity manager
            return null;

        // Check station name if it is set and exit if it doesn't match the current grid
        // The checking will be skipped if StationName is not set
        if (component.StationName != null && component.StationName != shuttleMeta.EntityName)
            return null;

        Log.Debug($"AssignDeeds called with idUid={uid}, shuttleUid={gridUid}, name={shuttleMeta.EntityName}");
        AssignDeeds(uid, gridUid, shuttleMeta, !component.Unique, true);
        return transform.GridUid;
    }
}
