using Content.Shared._NF.Shipyard.Components;

namespace Content.Shared._AS.Shuttles.Deeds;

/// <summary>
///     Exists just so AutoGenerateDeedSystem has write access to <see cref="ShuttleDeedComponent"/>
/// </summary>
public abstract class SharedAutoGenerateDeedSystem : EntitySystem { }
