using System.Linq;
using Content.Shared.Body;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class OrganMarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _marking = default!;
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly HashSet<HumanoidVisualLayers> _layers;
    private readonly ProtoId<MarkingsGroupPrototype> _group;
    private readonly ProtoId<OrganCategoryPrototype> _organ;

    public OrganMarkingPicker(MarkingsViewModel markingsModel, ProtoId<OrganCategoryPrototype> organ, HashSet<HumanoidVisualLayers> layers, ProtoId<MarkingsGroupPrototype> group)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _layers = layers;
        _group = group;
        _organ = organ;

        _sprite = _entity.System<SpriteSystem>();

        UpdateMarkings();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.OrganProfileDataChanged += OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.OrganProfileDataChanged -= OnOrganProfileDataChanged;
        _markingsModel.EnforcementsChanged -= UpdateMarkings;
    }

    public bool Empty => LayerTabs.ChildCount == 0;

    private void OnOrganProfileDataChanged(bool refresh)
    {
        if (refresh)
            UpdateMarkings();
    }

    private void UpdateMarkings()
    {
        if (!_markingsModel.OrganProfileData.TryGetValue(_organ, out var organProfileData))
            return;

        LayerTabs.RemoveAllChildren();
        var i = 0;
        foreach (var layer in _layers)
        {
            var allMarkings =
                _markingsModel.EnforceGroupAndSexRestrictions ? _marking.MarkingsByLayerAndGroupAndSex(layer, _group, organProfileData.Sex) : _marking.MarkingsByLayer(layer);

            if (allMarkings.Count == 0)
                continue;

            // Aurora's Song - Sort markings based on preferred species.
            // Preferred species > no species preference > non-preferred species
            // (then sort by name)
            var sortedMarkings = allMarkings
                .OrderBy(m => GetPreferredSpeciesPriority(m.Value)).ToDictionary();

            var control = new LayerMarkingPicker(_markingsModel, _organ, layer, sortedMarkings); // Aurora's Song - Marking preference
            LayerTabs.AddChild(control);
            if (Loc.TryGetString($"markings-layer-{layer}-{_group.Id}", out var layerTitle))
                LayerTabs.SetTabTitle(i, layerTitle);
            else
                LayerTabs.SetTabTitle(i, Loc.GetString($"markings-layer-{layer}"));
            i++;
        }

        LayerTabs.TabsVisible = i > 1;
    }

    // Aurora's Song - Sort markings based on preferred species.
    // Preferred species > no species preference > non-preferred species
    private int GetPreferredSpeciesPriority(MarkingPrototype prototype)
    {
        var preferred = prototype.PreferredGroup;
        if (preferred is null)
            return 1;

        return preferred.Contains(_group) ? 0 : 2;
    }
    // End AuroraSong
}
