using System.Linq;
using Content.Shared._AS.BountyContracts.Prototypes; // Aurora Song
using Content.Shared._NF.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._NF.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentCreate : Control
{
    [Dependency] IPrototypeManager _proto = default!;
    public event Action<BountyContractRequest>? OnCreatePressed;
    public event Action? OnCancelPressed;

    private List<BountyContractTargetInfo> _targets = new();
    private List<string> _vessels = new();
    private ProtoId<BountyContractCollectionPrototype> _collection;

    // Aurora Song - cached alphabetical prototype list
    private List<ProtoId<BountyContractCategoryPrototype>> _categories = default!; // This gets initialized in FillCategories().

    public BountyContractUiFragmentCreate(ProtoId<BountyContractCollectionPrototype> collection)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        CategorySelector.OnItemSelected += opt => OnCategorySelected(opt.Id);
        NameSelector.OnItemSelected += opt => OnNameSelected(opt.Id);
        VesselSelector.OnItemSelected += opt => OnVesselSelected(opt.Id);

        CustomNameButton.OnToggled += args => OnCustomNameToggle(args.Pressed);
        CustomVesselButton.OnToggled += args => OnCustomVesselToggle(args.Pressed);
        NameEdit.OnTextChanged += _ => UpdateDisclaimer();
        RewardEdit.OnTextChanged += _ => UpdateDisclaimer();
        VesselEdit.OnTextChanged += _ => UpdateDisclaimer();

        var descPlaceholder = Loc.GetString("bounty-contracts-ui-create-description-placeholder");
        DescriptionEdit.Placeholder = new Rope.Leaf(descPlaceholder);
        DescriptionEdit.OnTextChanged += _ => UpdateDisclaimer();
        RewardEdit.Text = SharedBountyContractSystem.DefaultReward.ToString();

        CreateButton.OnPressed += _ => OnCreatePressed?.Invoke(GetBountyContract());
        CancelButton.OnPressed += _ => OnCancelPressed?.Invoke();

        _collection = collection;

        // start Aurora Song - account for category changes
        _proto.PrototypesReloaded += args =>
        {
            if (args.WasModified<BountyContractCategoryPrototype>())
                FillCategories(); // This will refresh the category collection.
        };
        // end Aurora Song

        FillCategories();
        UpdateDisclaimer();
    }

    public void SetPossibleTargets(List<BountyContractTargetInfo> targets)
    {
        // make sure that all targets sorted by names alphabetically
        _targets = targets.OrderBy(target => target.Name).ToList();

        // update names dropdown
        NameSelector.Clear();
        for (var i = 0; i < _targets.Count; i++)
        {
            NameSelector.AddItem(_targets[i].Name, i);
        }

        // set selector to first option
        OnNameSelected(0);
    }

    public void SetVessels(List<string> vessels)
    {
        // make sure that all ships sorted by names alphabetically
        vessels.Sort();

        // add unknown option as a first option
        vessels.Insert(0, Loc.GetString("bounty-contracts-ui-create-vessel-unknown"));
        _vessels = vessels;

        // update ships dropdown
        VesselSelector.Clear();
        for (var i = 0; i < _vessels.Count; i++)
        {
            if (string.IsNullOrWhiteSpace(_vessels[i]))
                continue;

            VesselSelector.AddItem(_vessels[i], i);
        }

        // set vessel to unknown
        OnVesselSelected(0);
    }

    // Start Aurora Song - cache categories for indexing
    /// <summary>
    ///     Caches bounty contract category prototypes as an alphabetical list,
    ///     so they can be indexed numerically.
    /// </summary>
    private void CacheCategoryPrototypes()
    {
        _categories = [.. _proto.EnumeratePrototypes<BountyContractCategoryPrototype>()
            .Select(p => (ProtoId<BountyContractCategoryPrototype>)p.ID)
            .OrderDescending()];
    }
    // End Aurora Song

    private void FillCategories()
    {
        if (!_proto.TryIndex(_collection, out var collectionProto))
            return;

        // start Aurora Song - use prototypes

        // We're clearing this out to make sure we have a clean slate and we're up-to-date on categories.
        CategorySelector.Clear();
        CacheCategoryPrototypes();

        foreach (var id in collectionProto.Categories)
        {

            // if (!SharedBountyContractSystem.CategoriesMeta.ContainsKey(id))
            //     continue;
            // var meta = SharedBountyContractSystem.CategoriesMeta[id];

            if (!_proto.TryIndex(id, out var meta))
                continue;

            var name = Loc.GetString(meta.Name);
            CategorySelector.AddItem(name, _categories.IndexOf(id));
        }

        // end Aurora Song
    }

    private void UpdateDna(string? dnaStr)
    {
        if (string.IsNullOrEmpty(dnaStr))
        {
            DnaBox.Visible = false;
            return;
        }

        DnaBox.Visible = true;
        DnaLabel.Text = dnaStr;
    }

    private void OnNameSelected(int itemIndex)
    {
        if (itemIndex >= _targets.Count)
            return;

        NameSelector.SelectId(itemIndex);

        // update dna
        var selectedTarget = _targets[itemIndex];
        var dnaStr = selectedTarget.DNA;
        UpdateDna(dnaStr);

        UpdateDisclaimer();
    }

    private void OnVesselSelected(int itemIndex)
    {
        if (itemIndex >= _vessels.Count)
            return;

        VesselSelector.SelectId(itemIndex);
    }

    private void OnCategorySelected(int objId)
    {
        // start Aurora Song - Use prototypes

        // var cat = (BountyContractCategory)objId;
        // CustomNameButton.Pressed = cat != BountyContractCategory.Criminal;

        var cat = GetCategory(objId);
        if (_proto.TryIndex(cat, out var category))
            CustomNameButton.Pressed = category.CustomNameDefault;

        // end Aurora Song

        OnCustomNameToggle(CustomNameButton.Pressed);

        CategorySelector.SelectId(objId);
    }

    private void OnCustomNameToggle(bool isPressed)
    {
        NameSelector.Visible = !isPressed;
        NameEdit.Visible = isPressed;

        UpdateDna(GetTargetDna());
        UpdateDisclaimer();
    }

    private void OnCustomVesselToggle(bool isPressed)
    {
        VesselSelector.Visible = !isPressed;
        VesselEdit.Visible = isPressed;

        OnVesselSelected(0);
    }

    private void UpdateDisclaimer()
    {
        // check if reward is valid
        var reward = GetReward();
        if (reward == null || reward < 0)
        {
            var err = Loc.GetString("bounty-contracts-ui-create-error-invalid-price");
            DisclaimerLabel.SetMessage(err);
            CreateButton.Disabled = true;
            return;
        }

        // check if name is valid
        var name = GetTargetName();
        if (name == "")
        {
            var err = Loc.GetString("bounty-contracts-ui-create-error-no-name");
            DisclaimerLabel.SetMessage(err);
            CreateButton.Disabled = true;
            return;
        }

        if (name.Length > SharedBountyContractSystem.MaxNameLength)
        {
            var err = Loc.GetString("bounty-contracts-ui-create-error-name-too-long");
            DisclaimerLabel.SetMessage(err);
            CreateButton.Disabled = true;
            return;
        }

        if (VesselEdit.Text.Length > SharedBountyContractSystem.MaxVesselLength)
        {
            var err = Loc.GetString("bounty-contracts-ui-create-error-vessel-name-too-long");
            DisclaimerLabel.SetMessage(err);
            CreateButton.Disabled = true;
            return;
        }

        if (DescriptionEdit.TextLength > SharedBountyContractSystem.MaxDescriptionLength)
        {
            var err = Loc.GetString("bounty-contracts-ui-create-error-description-too-long");
            DisclaimerLabel.SetMessage(err);
            CreateButton.Disabled = true;
            return;
        }

        // all looks good
        DisclaimerLabel.SetMessage(Loc.GetString("bounty-contracts-ui-create-ready"));
        CreateButton.Disabled = false;
    }

    public int? GetReward()
    {
        var priceStr = RewardEdit.Text;
        return int.TryParse(priceStr, out var price) ? price : null;
    }

    public BountyContractTargetInfo? GetTargetInfo()
    {
        BountyContractTargetInfo? info = null;
        if (!CustomNameButton.Pressed)
        {
            var id = NameSelector.SelectedId;
            if (id < _targets.Count)
                info = _targets[id];
        }
        else
        {
            info = new BountyContractTargetInfo
            {
                Name = NameEdit.Text,
                DNA = null
            };
        }

        return info;
    }

    public string GetTargetName()
    {
        var info = GetTargetInfo();
        return info != null ? info.Value.Name : "";
    }

    public string? GetTargetDna()
    {
        var info = GetTargetInfo();
        return info?.DNA;
    }

    public string GetVessel()
    {
        var vessel = "";

        if (!CustomVesselButton.Pressed)
        {
            var id = VesselSelector.SelectedId;
            if (id < _vessels.Count)
                vessel = _vessels[id];
        }
        else
        {
            vessel = VesselEdit.Text;
        }

        return vessel;
    }

    // start Aurora Song: Use prototypes

    // public BountyContractCategory GetCategory()
    // {
    //     return (BountyContractCategory)CategorySelector.SelectedId;
    // }

    public ProtoId<BountyContractCategoryPrototype> GetCategory(int? id = null)
    {
        id ??= CategorySelector.SelectedId;

        if (!_categories.TryGetValue(id.Value, out var category))
            return SharedBountyContractSystem.FallbackCategory;

        return category;
    }

    // end Aurora Song

    public BountyContractRequest GetBountyContract()
    {
        var info = new BountyContractRequest
        {
            Collection = _collection,
            Category = GetCategory(),
            Name = GetTargetName(),
            DNA = GetTargetDna(),
            Vessel = GetVessel(),
            Description = Rope.Collapse(DescriptionEdit.TextRope),
            Reward = GetReward() ?? 0
        };
        return info;
    }
}
