// SPDX-FileCopyrightText: 2026 Dirius77
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DEN.Holosign.UI;

[GenerateTypedNameReferences]
public sealed partial class LabelableHolosignProjectorWindow : DefaultWindow
{
    public event Action<string>? OnDescriptionChanged;

    private string _description = string.Empty;

    public LabelableHolosignProjectorWindow()
    {
        RobustXamlLoader.Load(this);

        DescriptionTextEdit.OnTextChanged += e =>
        {
            var text = Rope.Collapse(e.TextRope).Trim();
            _description = text;
            OnDescriptionChanged?.Invoke(_description);
        };
    }

    public void SetCurrentDescription(string description)
    {
        if (description == _description)
            return;

        _description = description;
        if (!DescriptionTextEdit.HasKeyboardFocus())
        {
            var rope = new Rope.Leaf(description);
            DescriptionTextEdit.TextRope = rope;
        }
    }
}
